In [34]:
import numpy as np
import scipy.linalg as sla
import matplotlib.pyplot as plt
from numpy import linalg as LA

In [2]:
def W_i(k):
    low = np.zeros((k, k))
    for i in range(k):
        if i == 0 or i == k - 1:
            low[i][i] = k + 1
        else:
            low[i][i] = k
    return low - np.ones((k, k))


In [3]:
W_i(3)

array([[ 3., -1., -1.],
       [-1.,  2., -1.],
       [-1., -1.,  3.]])

In [4]:
def W_old(k, n):
    matr = np.kron(np.eye(n), W_i(k))
    for j in range(n):
        matr[j * k - 1][j * k] = -1
        matr[j * k][j * k - 1] = -1
    return matr

In [5]:
W_old(3,3)

array([[ 3., -1., -1.,  0., -0., -0.,  0., -0., -1.],
       [-1.,  2., -1., -0.,  0., -0., -0.,  0., -0.],
       [-1., -1.,  3., -1., -0.,  0., -0., -0.,  0.],
       [ 0., -0., -1.,  3., -1., -1.,  0., -0., -0.],
       [-0.,  0., -0., -1.,  2., -1., -0.,  0., -0.],
       [-0., -0.,  0., -1., -1.,  3., -1., -0.,  0.],
       [ 0., -0., -0.,  0., -0., -1.,  3., -1., -1.],
       [-0.,  0., -0., -0.,  0., -0., -1.,  2., -1.],
       [-1., -0.,  0., -0., -0.,  0., -1., -1.,  3.]])

In [6]:
def W_new(k,n):
    matr = np.kron(W_i(k),np.eye(n))
    return matr

In [7]:
W_new(4,3)

array([[ 4.,  0.,  0., -1., -0., -0., -1., -0., -0., -1., -0., -0.],
       [ 0.,  4.,  0., -0., -1., -0., -0., -1., -0., -0., -1., -0.],
       [ 0.,  0.,  4., -0., -0., -1., -0., -0., -1., -0., -0., -1.],
       [-1., -0., -0.,  3.,  0.,  0., -1., -0., -0., -1., -0., -0.],
       [-0., -1., -0.,  0.,  3.,  0., -0., -1., -0., -0., -1., -0.],
       [-0., -0., -1.,  0.,  0.,  3., -0., -0., -1., -0., -0., -1.],
       [-1., -0., -0., -1., -0., -0.,  3.,  0.,  0., -1., -0., -0.],
       [-0., -1., -0., -0., -1., -0.,  0.,  3.,  0., -0., -1., -0.],
       [-0., -0., -1., -0., -0., -1.,  0.,  0.,  3., -0., -0., -1.],
       [-1., -0., -0., -1., -0., -0., -1., -0., -0.,  4.,  0.,  0.],
       [-0., -1., -0., -0., -1., -0., -0., -1., -0.,  0.,  4.,  0.],
       [-0., -0., -1., -0., -0., -1., -0., -0., -1.,  0.,  0.,  4.]])

In [8]:
def cond_num(m):
    v = sla.svd(m)
    return v[1][0]/v[1][-2]

In [ ]:
%timeit arr = star_laplacian(10000)

In [37]:
def A(d1,d2, setnodes):
    #setnodes - множество значений переменных, от которых есть зависимость
    #то есть зависит от x1,x2 - setnodes = {1,2}
    A = np.random.rand(d1,d2)
    for i in setnodes:
        A[:,i] = 0
    return A
def b(d1):
    return np.random.rand(d1,1)
def f(A,b):
    return 0.5*LA.norm(A.dot(x) - b)**2

In [38]:
x = np.random.rand(4,1) #у x размерность d2
print(f(A(3,4,{0,1}), b(3))) #тестовый пример подсчета функции

0.9412283382139881


In [41]:
#минимизировать f(x) при ограничениях Wx = 0 для новой и старой W
def decentralized_gd(f,W):
    pass